In [4]:
# getting the link from api

import requests
import pandas as pd
import json

url = "https://datamall2.mytransport.sg/ltaodataservice/EVCBatch"

payload = {}
headers = {
  'Accept': 'application/json',
  'accountkey': '' # input your LTA datamall API account key
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

print("✅ Libraries imported!")
print(f"   requests version : {requests.__version__}")
print(f"   pandas version   : {pd.__version__}")

{"odata.metadata":"https://datamall2.mytransport.sg/ltaodataservice/$metadata#evcBatch","value":[{"Link":"https://dmprod-datasets.s3.ap-southeast-1.amazonaws.com/ev-batch/2026-08-16/EVBatch-20260816163007.json?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGAaDmFwLXNvdXRoZWFzdC0xIkcwRQIhAIUI0fMSV2NM9qzTMQwpxsYPLTqq%2B8eqrIKw3N4a%2BC6rAiAjZ09PneC7fD2TVyPpbs3frYTpWyzmJtgdfkO0DTekoyrCBQgpEAQaDDM0MDY0NTM4MTMwNCIMNfDWkTcmVknW81tdKp8FKvnB0hitNtJELVmC6mr%2BFiOimz4Muf5%2B0micnQEpjuxttU8UYlf2%2BaumBpCzE7ESnYc6hthAi9Zb6JtPPwUSbBSQ6AX%2Fej1MNXPJBRdTIBqMSISl6pwxCPuD4qjkmJDa0Fs7SGbz0rXQrTRv4iiTSA1IVUhc6D30zXW6KdhonlYcGT3YywVAY5sjEpxsw1%2F8t0BJ6z1CBp0%2FkUj7eSIPbk5%2FpBu%2BJa1eM2jbg2w6hUzxlOCdld5enMQF4fjZFdANFgm%2F8nqz5wQu%2BN1Ye2EmZBBJkz%2BWCY31Q73xzzyjEMfVNqUyxG0ClAIMbkPWwFPcg4PyicmU9N7Oa4QeT5B8goZufUytwjj5Fl4hT5IQbECl%2BCXK0SagwrqOmxRrI3xfPJKSKG%2BFM4tXx870hCfN0nVgZUoQ8FaqQaTMcCKhaGo36CwfPBj4te540famJXRV3YDT1j8qwYQjsh2aQkpyVhsfv9EogLqZkeIRf937Yiy74X6XAmOwm11TWem38t%2FPpxu3mFFZwCk8KZ8l9%2BAsZXmOWGospue8%2BmNqZIf%2Fapm3IFprM0boFDvjM0tFG%2FFZ4oRaokKNHYbcIXjbhoOgWBtLhgPt9D1namB4Jpuyf8ovPXPJWkQLnIBndpReyQKHH3rWN5PraRrj78Y5yqWYwrKkxfuPigiXAI8C2XvFCbCPtOzPWkpIr1qU6IMxuY%2FUbeu1JZ5H19Zsn%2F75xH9UexsdKffNPX%2FS3Tl2geNUn5%2BOztud6QqnDwDJGseNSYF5elkNo65g1ZwtH7WZCHR%2BKT3wlJVpor3fNob%2BSgiIvLOPhQWfMInlXh6EXxbofQxgXfQ2oJ3gaoPAqqJY9aBIQTQYJtE5FSTiJIGAP4rdlBEZTH%2F5oKRuo%2Bzxz98w4qUwuc%2BF1AY6sQHHQWZk5NWiibKkRzKLZDTLHmFXqlfhVz3xaJMkzjwwCutTvUtv8IGNjs9dx%2BTd%2Fts9kEk8ANS6ed5wx9hD8NrYF%2FN71lfx8NdbcOq8K2TZEyyBKtuaH%2BGtZuD3DwAgjvvk426mkatxm3jYYnjLNzaucC453RDF2NIJ2D69GsMdWBnWh%2FlSszjBXzZABBDz9uk6BuqGY97fOzZCVmNJIWXQmv%2BLJE1DVfBve9jiamYI2A8%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260816T083317Z&X-Amz-SignedHeaders=host&X-Amz-Expires=299&X-Amz-Credential=ASIAU6UAMAS4DO6QBZQU%2F20260816%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=d4594ed1db8b671de6492b25466c46ac799744162e8661a1c7c010bc79557fab"}]}
✅ Libraries imported!
   requests version : 2.32.5
   pandas version   : 2.3.3

In [5]:
# Convert JSON response to Python dictionary

data = response.json()

print(f"Type of data       : {type(data)}")
print(f"Top-level keys     : {list(data.keys())}")

Type of data       : <class 'dict'>
Top-level keys     : ['odata.metadata', 'value']

In [6]:
# Inspect the nested structure
# This API uses 'value' as the key containing records

print(f"Number of records  : {len(data.get('value', []))}") 
print()

# Preview first record
# json.dumps() method can convert a Python object into a JSON string.
if data.get('value'):
    print(json.dumps(data['value'][0]["Link"]))

Number of records  : 1

"https://dmprod-datasets.s3.ap-southeast-1.amazonaws.com/ev-batch/2026-08-16/EVBatch-20260816163007.json?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGAaDmFwLXNvdXRoZWFzdC0xIkcwRQIhAIUI0fMSV2NM9qzTMQwpxsYPLTqq%2B8eqrIKw3N4a%2BC6rAiAjZ09PneC7fD2TVyPpbs3frYTpWyzmJtgdfkO0DTekoyrCBQgpEAQaDDM0MDY0NTM4MTMwNCIMNfDWkTcmVknW81tdKp8FKvnB0hitNtJELVmC6mr%2BFiOimz4Muf5%2B0micnQEpjuxttU8UYlf2%2BaumBpCzE7ESnYc6hthAi9Zb6JtPPwUSbBSQ6AX%2Fej1MNXPJBRdTIBqMSISl6pwxCPuD4qjkmJDa0Fs7SGbz0rXQrTRv4iiTSA1IVUhc6D30zXW6KdhonlYcGT3YywVAY5sjEpxsw1%2F8t0BJ6z1CBp0%2FkUj7eSIPbk5%2FpBu%2BJa1eM2jbg2w6hUzxlOCdld5enMQF4fjZFdANFgm%2F8nqz5wQu%2BN1Ye2EmZBBJkz%2BWCY31Q73xzzyjEMfVNqUyxG0ClAIMbkPWwFPcg4PyicmU9N7Oa4QeT5B8goZufUytwjj5Fl4hT5IQbECl%2BCXK0SagwrqOmxRrI3xfPJKSKG%2BFM4tXx870hCfN0nVgZUoQ8FaqQaTMcCKhaGo36CwfPBj4te540famJXRV3YDT1j8qwYQjsh2aQkpyVhsfv9EogLqZkeIRf937Yiy74X6XAmOwm11TWem38t%2FPpxu3mFFZwCk8KZ8l9%2BAsZXmOWGospue8%2BmNqZIf%2Fapm3IFprM0boFDvjM0tFG%2FFZ4oRaokKNHYbcIXjbhoOgWBtLhgPt9D1namB4Jpuyf8ovPXPJWkQLnIBndpReyQKHH3rWN5PraRrj78Y5yqWYwrKkxfuPigiXAI8C2XvFCbCPtOzPWkpIr1qU6IMxuY%2FUbeu1JZ5H19Zsn%2F75xH9UexsdKffNPX%2FS3Tl2geNUn5%2BOztud6QqnDwDJGseNSYF5elkNo65g1ZwtH7WZCHR%2BKT3wlJVpor3fNob%2BSgiIvLOPhQWfMInlXh6EXxbofQxgXfQ2oJ3gaoPAqqJY9aBIQTQYJtE5FSTiJIGAP4rdlBEZTH%2F5oKRuo%2Bzxz98w4qUwuc%2BF1AY6sQHHQWZk5NWiibKkRzKLZDTLHmFXqlfhVz3xaJMkzjwwCutTvUtv8IGNjs9dx%2BTd%2Fts9kEk8ANS6ed5wx9hD8NrYF%2FN71lfx8NdbcOq8K2TZEyyBKtuaH%2BGtZuD3DwAgjvvk426mkatxm3jYYnjLNzaucC453RDF2NIJ2D69GsMdWBnWh%2FlSszjBXzZABBDz9uk6BuqGY97fOzZCVmNJIWXQmv%2BLJE1DVfBve9jiamYI2A8%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260816T083317Z&X-Amz-SignedHeaders=host&X-Amz-Expires=299&X-Amz-Credential=ASIAU6UAMAS4DO6QBZQU%2F20260816%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=d4594ed1db8b671de6492b25466c46ac799744162e8661a1c7c010bc79557fab"

In [7]:
# getting rid of " in the url

new_url = json.dumps(data['value'][0]['Link']).strip('"')
new_url

'https://dmprod-datasets.s3.ap-southeast-1.amazonaws.com/ev-batch/2026-08-16/EVBatch-20260816163007.json?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGAaDmFwLXNvdXRoZWFzdC0xIkcwRQIhAIUI0fMSV2NM9qzTMQwpxsYPLTqq%2B8eqrIKw3N4a%2BC6rAiAjZ09PneC7fD2TVyPpbs3frYTpWyzmJtgdfkO0DTekoyrCBQgpEAQaDDM0MDY0NTM4MTMwNCIMNfDWkTcmVknW81tdKp8FKvnB0hitNtJELVmC6mr%2BFiOimz4Muf5%2B0micnQEpjuxttU8UYlf2%2BaumBpCzE7ESnYc6hthAi9Zb6JtPPwUSbBSQ6AX%2Fej1MNXPJBRdTIBqMSISl6pwxCPuD4qjkmJDa0Fs7SGbz0rXQrTRv4iiTSA1IVUhc6D30zXW6KdhonlYcGT3YywVAY5sjEpxsw1%2F8t0BJ6z1CBp0%2FkUj7eSIPbk5%2FpBu%2BJa1eM2jbg2w6hUzxlOCdld5enMQF4fjZFdANFgm%2F8nqz5wQu%2BN1Ye2EmZBBJkz%2BWCY31Q73xzzyjEMfVNqUyxG0ClAIMbkPWwFPcg4PyicmU9N7Oa4QeT5B8goZufUytwjj5Fl4hT5IQbECl%2BCXK0SagwrqOmxRrI3xfPJKSKG%2BFM4tXx870hCfN0nVgZUoQ8FaqQaTMcCKhaGo36CwfPBj4te540famJXRV3YDT1j8qwYQjsh2aQkpyVhsfv9EogLqZkeIRf937Yiy74X6XAmOwm11TWem38t%2FPpxu3mFFZwCk8KZ8l9%2BAsZXmOWGospue8%2BmNqZIf%2Fapm3IFprM0boFDvjM0tFG%2FFZ4oRaokKNHYbcIXjbhoOgWBtLhgPt9D1namB4Jpuyf8ovPXPJWkQLnIBndpReyQKHH3rWN5PraRrj78Y5yqWYwrKkxfuPigiXAI8C2XvFCbCPtOzPWkpIr1qU6IMxuY%2FUbeu1JZ5H19Zsn%2F75xH9UexsdKffNPX%2FS3Tl2geNUn5%2BOztud6QqnDwDJGseNSYF5elkNo65g1ZwtH7WZCHR%2BKT3wlJVpor3fNob%2BSgiIvLOPhQWfMInlXh6EXxbofQxgXfQ2oJ3gaoPAqqJY9aBIQTQYJtE5FSTiJIGAP4rdlBEZTH%2F5oKRuo%2Bzxz98w4qUwuc%2BF1AY6sQHHQWZk5NWiibKkRzKLZDTLHmFXqlfhVz3xaJMkzjwwCutTvUtv8IGNjs9dx%2BTd%2Fts9kEk8ANS6ed5wx9hD8NrYF%2FN71lfx8NdbcOq8K2TZEyyBKtuaH%2BGtZuD3DwAgjvvk426mkatxm3jYYnjLNzaucC453RDF2NIJ2D69GsMdWBnWh%2FlSszjBXzZABBDz9uk6BuqGY97fOzZCVmNJIWXQmv%2BLJE1DVfBve9jiamYI2A8%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20260816T083317Z&X-Amz-SignedHeaders=host&X-Amz-Expires=299&X-Amz-Credential=ASIAU6UAMAS4DO6QBZQU%2F20260816%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=d4594ed1db8b671de6492b25466c46ac799744162e8661a1c7c010bc79557fab'

In [8]:
response1 = requests.request("GET", new_url, headers=headers, data=payload)

print(response1.text[:300])

{"LastUpdatedTime":"2026-08-16 16:30:00","evLocationsData":[{"address":"3E RIVER VALLEY ROAD SINGAPORE 179024","name":"CLARKE QUAY","longtitude":103.846728,"latitude":1.290314,"postalCode":"179024","chargingPoints":[{"status":"1","operatingHours":"","operator":"SP MOBILITY PTE. LTD.","position":"L4

In [9]:
# Inspect the nested structure
# This API uses 'evLocationsData' as the key containing records

new_data = response1.json()

print(f"Type of data       : {type(new_data)}")
print(f"Top-level keys     : {list(new_data.keys())}")

Type of data       : <class 'dict'>
Top-level keys     : ['LastUpdatedTime', 'evLocationsData']

In [10]:
# checking number of records
print(f"Number of records  : {len(new_data.get('evLocationsData', []))}") 
print()

# Preview first record
# json.dumps() method can convert a Python object into a JSON string.
if new_data.get('evLocationsData'):
    print("First record (formatted):")
    print(json.dumps(new_data['evLocationsData'][0], indent=2))
    print("Second record (formatted):")
    print(json.dumps(new_data['evLocationsData'][1], indent=2))

Number of records  : 2730

First record (formatted):
{
  "address": "3E RIVER VALLEY ROAD SINGAPORE 179024",
  "name": "CLARKE QUAY",
  "longtitude": 103.846728,
  "latitude": 1.290314,
  "postalCode": "179024",
  "chargingPoints": [
    {
      "status": "1",
      "operatingHours": "",
      "operator": "SP MOBILITY PTE. LTD.",
      "position": "L4 51 & 52",
      "name": "CLARKE QUAY",
      "plugTypes": [
        {
          "plugType": "Combo 2",
          "price": "0.8938",
          "current": "DC",
          "powerRating": "50",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R114858R-001",
              "status": "1"
            },
            {
              "evCpId": "R114858R-002",
              "status": "1"
            }
          ]
        }
      ]
    },
    {
      "status": "1",
      "operatingHours": "",
      "operator": "SP MOBILITY PTE. LTD.",
      "position": "L4 49",
      "name": "CLARKE QUAY",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.8066",
          "current": "AC",
          "powerRating": "22",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R114859D-001",
              "status": "1"
            }
          ]
        }
      ]
    },
    {
      "status": "1",
      "operatingHours": "",
      "operator": "SP MOBILITY PTE. LTD.",
      "position": "L4 50",
      "name": "CLARKE QUAY",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.8066",
          "current": "AC",
          "powerRating": "22",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R114861R-001",
              "status": "1"
            }
          ]
        }
      ]
    }
  ]
}
Second record (formatted):
{
  "address": "142A PASIR RIS STREET 11 SINGAPORE 511142",
  "name": "BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR PARK",
  "longtitude": 103.959758,
  "latitude": 1.362839,
  "postalCode": "511142",
  "chargingPoints": [
    {
      "status": "0",
      "operatingHours": "",
      "operator": "STRIDES YTL PTE. LTD.",
      "position": "L3A 128",
      "name": "BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR PARK",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.6980",
          "current": "AC",
          "powerRating": "7.4",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R122901R-001",
              "status": "0"
            }
          ]
        }
      ]
    },
    {
      "status": "0",
      "operatingHours": "",
      "operator": "STRIDES YTL PTE. LTD.",
      "position": "L3A 127",
      "name": "BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR PARK",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.6980",
          "current": "AC",
          "powerRating": "7.4",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R122900G-001",
              "status": "0"
            }
          ]
        }
      ]
    },
    {
      "status": "1",
      "operatingHours": "",
      "operator": "STRIDES YTL PTE. LTD.",
      "position": "L3A 129",
      "name": "BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR PARK",
      "plugTypes": [
        {
          "plugType": "Type 2",
          "price": "0.6980",
          "current": "AC",
          "powerRating": "7.4",
          "priceType": "kWh",
          "evIds": [
            {
              "evCpId": "R122902D-001",
              "status": "1"
            }
          ]
        }
      ]
    }
  ]
}

In [11]:
# Use pd.json_normalize to flatten 'evLocationsData' → 'attributes' into a DataFrame

df_location = pd.json_normalize(new_data, 'evLocationsData')

print(f"Shape : {df_location.shape}")
df_location.head(5)

Shape : (2730, 6)

,address,name,longtitude,latitude,postalCode,chargingPoints
0,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,"[{'status': '1', 'operatingHours': '', 'operat..."
1,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,"[{'status': '0', 'operatingHours': '', 'operat..."
2,207A BISHAN STREET 23 SINGAPORE 571207,BLK 207A BISHAN STREET 23,103.848309,1.355154,571207,"[{'status': '1', 'operatingHours': '', 'operat..."
3,113 BUKIT BATOK WEST AVENUE 6 SINGAPORE 650113,BLK 111/132 BUKIT BATOK WEST AVENUE 6,103.746309,1.349872,650113,"[{'status': '1', 'operatingHours': '', 'operat..."
4,640A JURONG WEST STREET 61 SINGAPORE 641640,BLK 640A JURONG WEST STREET 61 MULTI STOREY CA...,103.696043,1.339733,641640,"[{'status': '1', 'operatingHours': '', 'operat..."

In [12]:
# Use pd.json_normalize to flatten 'chargingPoints' → 'attributes' into a DataFrame

df_chargingpoints = pd.json_normalize(new_data['evLocationsData'], 'chargingPoints')

print(f"Shape : {df_chargingpoints.shape}")
df_chargingpoints.head(5)

Shape : (8904, 6)

,status,operatingHours,operator,position,name,plugTypes
0,1,,SP MOBILITY PTE. LTD.,L4 51 & 52,CLARKE QUAY,"[{'plugType': 'Combo 2', 'price': '0.8938', 'c..."
1,1,,SP MOBILITY PTE. LTD.,L4 49,CLARKE QUAY,"[{'plugType': 'Type 2', 'price': '0.8066', 'cu..."
2,1,,SP MOBILITY PTE. LTD.,L4 50,CLARKE QUAY,"[{'plugType': 'Type 2', 'price': '0.8066', 'cu..."
3,0,,STRIDES YTL PTE. LTD.,L3A 128,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu..."
4,0,,STRIDES YTL PTE. LTD.,L3A 127,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,"[{'plugType': 'Type 2', 'price': '0.6980', 'cu..."

In [13]:
# Use pd.json_normalize to flatten 'plugTypes' → 'attributes' into a DataFrame

dfs_plugtype = []

for i in range(len(new_data['evLocationsData'])):
    for j in range(len(new_data['evLocationsData'][i]['chargingPoints'])):
        df1 = pd.json_normalize(
            new_data['evLocationsData'][i]['chargingPoints'][j],
            'plugTypes'
        )
        dfs_plugtype.append(df1)

df_plugtype = pd.concat(dfs_plugtype, ignore_index=True)

print(f"Shape : {df_plugtype.shape}")
df_plugtype.head(5)

Shape : (9155, 6)

,plugType,price,current,powerRating,priceType,evIds
0,Combo 2,0.8938,DC,50,kWh,"[{'evCpId': 'R114858R-001', 'status': '1'}, {'..."
1,Type 2,0.8066,AC,22,kWh,"[{'evCpId': 'R114859D-001', 'status': '1'}]"
2,Type 2,0.8066,AC,22,kWh,"[{'evCpId': 'R114861R-001', 'status': '1'}]"
3,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122901R-001', 'status': '0'}]"
4,Type 2,0.6980,AC,7.4,kWh,"[{'evCpId': 'R122900G-001', 'status': '0'}]"

In [26]:
# Use pd.json_normalize to flatten 'evIds' → 'attributes' into a DataFrame

dfs_evids = []

for i in range(len(new_data['evLocationsData'])):
    for j in range(len(new_data['evLocationsData'][i]['chargingPoints'])):
        for k in range(len(new_data['evLocationsData'][i]['chargingPoints'][j]['plugTypes'])):
            df2 = pd.json_normalize(
                new_data['evLocationsData'][i]['chargingPoints'][j]['plugTypes'][k],
                'evIds'
                )
            dfs_evids.append(df2)

df_evids = pd.concat(dfs_evids, ignore_index=True)

print(f"Shape : {df_evids.shape}")
#df_evids.head(5)

Shape : (11308, 2)

In [15]:
# use for loop to flatten out all the nested structure and combine all into 1 big table

records = []

for location in new_data['evLocationsData']:
    
    for charging_point in location['chargingPoints']:
        
        for plug_type in charging_point['plugTypes']:
            
            for ev_id in plug_type['evIds']:
                
                record = {
                    'address': location['address'],
                    'location_name': location['name'],
                    'longtitude': location['longtitude'],
                    'latitude': location['latitude'],
                    'postal_code': location['postalCode'],
                    
                    'chargingpoint_status': charging_point['status'],
                    'operating_hours': charging_point['operatingHours'],
                    'operator': charging_point['operator'],
                    'position': charging_point['position'],
                    'chargingpoint_name': charging_point['name'],
                    
                    'plug_type': plug_type['plugType'],
                    'price': plug_type['price'],
                    'current': plug_type['current'],
                    'power_rating': plug_type['powerRating'],
                    'price_type': plug_type['priceType'],
                    
                    'evcp_id': ev_id['evCpId'],
                    'evid_status': ev_id['status']
                }
                
                records.append(record)

df_main = pd.DataFrame(records)

print(f"Shape : {df_main.shape}")
df_main.head(5)

Shape : (11308, 17)

,address,location_name,longtitude,latitude,postal_code,chargingpoint_status,operating_hours,operator,position,chargingpoint_name,plug_type,price,current,power_rating,price_type,evcp_id,evid_status
0,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,1,,SP MOBILITY PTE. LTD.,L4 51 & 52,CLARKE QUAY,Combo 2,0.8938,DC,50,kWh,R114858R-001,1
1,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,1,,SP MOBILITY PTE. LTD.,L4 51 & 52,CLARKE QUAY,Combo 2,0.8938,DC,50,kWh,R114858R-002,1
2,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,1,,SP MOBILITY PTE. LTD.,L4 49,CLARKE QUAY,Type 2,0.8066,AC,22,kWh,R114859D-001,1
3,3E RIVER VALLEY ROAD SINGAPORE 179024,CLARKE QUAY,103.846728,1.290314,179024,1,,SP MOBILITY PTE. LTD.,L4 50,CLARKE QUAY,Type 2,0.8066,AC,22,kWh,R114861R-001,1
4,142A PASIR RIS STREET 11 SINGAPORE 511142,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,103.959758,1.362839,511142,0,,STRIDES YTL PTE. LTD.,L3A 128,BLK 142A PASIR RIS STREET 11 MULTI STOREY CAR ...,Type 2,0.6980,AC,7.4,kWh,R122901R-001,0

In [16]:
# converting to a more appropriate data type for each column

df_main.postal_code = df_main.postal_code.astype(int)
df_main.chargingpoint_status = df_main.chargingpoint_status.astype(int)
df_main.price = pd.to_numeric(df_main.price, errors='coerce')
df_main.evid_status = pd.to_numeric(df_main.evid_status, errors='coerce')

In [17]:
# check all column data type

df_main.dtypes

address                  object
location_name            object
longtitude              float64
latitude                float64
postal_code               int64
chargingpoint_status      int64
operating_hours          object
operator                 object
position                 object
chargingpoint_name       object
plug_type                object
price                   float64
current                  object
power_rating             object
price_type               object
evcp_id                  object
evid_status             float64
dtype: object

In [18]:
# check for null

missing = df_main.isna().sum()
missing

address                   0
location_name             0
longtitude                0
latitude                  0
postal_code               0
chargingpoint_status      0
operating_hours           0
operator                  0
position                  0
chargingpoint_name        0
plug_type                 0
price                   215
current                   0
power_rating              0
price_type                0
evcp_id                   0
evid_status             194
dtype: int64

In [19]:
# Check for duplicates

df_main.duplicated().sum()

np.int64(0)

In [20]:
import numpy as np
import sqlalchemy as db
from sqlalchemy_utils import create_database, database_exists
from sqlalchemy import text

print("✅ Libraries imported successfully!")
print(f"   SQLAlchemy version : {db.__version__}")
print(f"   Pandas version     : {pd.__version__}")

✅ Libraries imported successfully!
   SQLAlchemy version : 2.0.43
   Pandas version     : 2.3.3

In [21]:
# === CONFIGURE postgresql CONNECTION ===

USERNAME = '' 
PASSWORD = '' 
HOST     = '' 
PORT     = 
DB_NAME  = 'ev'

CONNECTION_STRING = f'postgresql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}'
print(f"Connection string: postgresql://{USERNAME}:****@{HOST}:{PORT}/{DB_NAME}")

Connection string: postgresql://postgres:****@localhost:5432/ev

In [29]:
# Create a new database (one-time operation)
engine = db.create_engine(CONNECTION_STRING)

if not database_exists(engine.url):
    create_database(engine.url)
    print(f"✅ Database '{DB_NAME}' created successfully!")
else:
    print(f"ℹ️  Database '{DB_NAME}' already exists — skipping creation.")

# Always dispose engine after use to free resources
engine.dispose()
print("Engine disposed (resources released).")

ℹ️  Database 'ev' already exists — skipping creation.
Engine disposed (resources released).

In [30]:
# i realised this step is not needed to load the dataframe straight into postgresql.
# can straight execute this line: df_main.to_sql(name='ev_main', con=engine, if_exists='append', index=False) 

commands = (
    # Table 1: ev_main — stores ev charing point data
    """
    DROP TABLE IF EXISTS ev_main;
    CREATE TABLE ev_main (
        address               TEXT,
        location_name         TEXT,
        longtitude            DOUBLE PRECISION,
        latitude              DOUBLE PRECISION,
        postal_code           INTEGER,
        chargingpoint_status  SMALLINT,
        operating_hours       TEXT,
        operator              TEXT,
        position              TEXT,
        chargingpoint_name    TEXT,
        plug_type             TEXT,
        price                 NUMERIC,
        current               VARCHAR(3),
        power_rating          NUMERIC,
        price_type            VARCHAR(5),
        evcp_id               TEXT,
        evid_status           SMALLINT
    );
    """,

    
)

# Execute all commands within a single transaction
with engine.begin() as conn:
    for command in commands:
        conn.execute(text(command))

print("✅ Tables 'ev_main' created successfully!")

✅ Tables 'ev_main' created successfully!

In [31]:
# Write DataFrame to the 'ev_main' table in PostgreSQL
rows_written = df_main.to_sql(
    name='ev_main',
    con=engine,
    if_exists='append',  # This is to append rows (Alternatively, use if_exists='replace', where appropriate)
    index=False          # Do not write DataFrame index as a column
)

print(f"✅ {rows_written} row(s) written to the 'ev_main' table.")

✅ 308 row(s) written to the 'ev_main' table.

challenges
- tried to flatten out each nested json like the chargingpoints, plugtype and evids. i assume i can load them as individual dataframe and load into postgresql as their own tables but realised i will not be able to relate them by the foreign keys.
- so i used for loop and create 1 big table instead and load into postgresql
- also need to ensure the tables in created in postgresql has the correct data types in order to load the dataframe into postgresql successfully.